2018-09-02 06:32:44,931 ERROR: Exception on /api/mood_texts [POST] [in c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Peggy Li\projects\bytehacks-2018\app\api\mood_texts.py", line 19, in create_text
    if isinstance(data.content, six.binary_type):
AttributeError: 'dict' object has no attribute 'content'
2018-09-02 06:33:34,804 INFO: Myapp startup [in C:\Users\Peggy Li\projects\bytehacks-2018\app\__init__.py:40]
2018-09-02 06:41:27,033 INFO: Myapp startup [in C:\Users\Peggy Li\projects\bytehacks-2018\app\__init__.py:40]
2018-09-02 06:44:12,730 INFO: Myapp startup [in C:\Users\Peggy Li\projects\bytehacks-2018\app\__init__.py:40]
2018-09-02 06:54:17,111 INFO: Myapp startup [in C:\Users\Peggy Li\projects\bytehacks-2018\app\__init__.py:40]
2018-09-02 07:00:38,264 INFO: Myapp startup [in C:\Users\Peggy Li\projects\bytehacks-2018\app\__init__.py:40]
2018-09-02 07:00:52,969 ERROR: Exception on /index [GET] [in c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Peggy Li\projects\bytehacks-2018\app\routes.py", line 27, in index
    return render_template('index.html', title='Home', posts=posts)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\peggy li\projects\bytehacks-2018\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Peggy Li\projects\bytehacks-2018\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Peggy Li\projects\bytehacks-2018\app\templates\base.html", line 37, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Peggy Li\projects\bytehacks-2018\app\templates\index.html", line 13, in block "content"
    {% if text.sentiment > 0 %}
TypeError: '>' not supported between instances of 'NoneType' and 'int'
2018-09-02 07:04:18,167 INFO: Myapp startup [in C:\Users\Peggy Li\projects\bytehacks-2018\app\__init__.py:40]
